# This file is part of Harden Role
# Copyright (C) 2014 Bill Carlson
#
#   This program is free software: you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation, either version 3 of the License, or
#   (at your option) any later version.
#
#   This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.
#
#   You should have received a copy of the GNU General Public License
#   along with this program.  If not, see <http://www.gnu.org/licenses/>.

---

- name: "CCE-26855-7: securetty_root_login_console_only"
  replace:
    dest=/etc/securetty
    regexp='^vc'

- name: "CCE-26974-6: set_system_login_banner"
  template:
    dest=/etc/issue
    src=issue

- name: "CCE-27040-5: require_singleuser_auth"
  lineinfile:
    dest=/etc/sysconfig/init
    line='SINGLE=/sbin/sulogin'
    regexp='^#*SINGLE'
  when:  ansible_os_family == 'RedHat'

- name: "CCE-27043-9: disable_interactive_boot"
  lineinfile:
    dest=/etc/sysconfig/init
    line='PROMPT=no'
    regexp='^#*PROMPT'
  when: ansible_os_family == 'RedHat'

- name: "CCE-26444-0: set_iptables_v4_default_rule"
  template:
    dest=/etc/iptables/rules.v4
    src="{{iptables_template}}"
  notify: restart iptables
  when: ansible_os_family == 'Debian' and iptables_provision
  tags: iptables
  
- name: "CCE-26444-0: set_iptables_default_rule, started"
  service:
    name=iptables-persistent
    state=started
    enabled=yes
  when: iptables_provision

- name: "CCE-27031-4: umask_for_daemons"
  lineinfile:
    dest=/etc/init.d/rc
    line="umask 027"
    regexp="^ *umask"

